# Generated by Django 3.0.8 on 2020-07-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comments_listing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bid',
            new_name='Bids',
        ),
        migrations.RenameModel(
            old_name='Listing',
            new_name='Listings',
        ),
    ]
