# Generated by Django 3.0.8 on 2020-07-18 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200717_2322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bids',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Listings',
        ),
    ]
