# Generated by Django 3.0.8 on 2020-07-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_listing_is_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_closed',
            new_name='is_open',
        ),
    ]
